### ISSUE TITLE
conda package for libde265

### ISSUE THREAD

**Issue by sebastian-luna-valero** [strukturag/libde265#227]
Hi,

I am building a conda package in conda-forge for  `libde265`, and I am getting the following compilation error:
```
libtool: compile:  $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++ -DHAVE_CONFIG_H -I. -I.. -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX/include -DLIBDE265_EXPORTS -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libde265-1.0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Werror=return-type -Werror=unused-result -Werror=reorder -DDE265_LOG_ERROR -MT libde265_la-dpb.lo -MD -MP -MF .deps/libde265_la-dpb.Tpo -c dpb.cc -o libde265_la-dpb.o >/dev/null 2>&1
image-io.cc: In member function 'virtual void ImageSink_YUV::send_image(const de265_image*)':
image-io.cc:164:11: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
     fwrite(p+y*stride,1,width,mFH);
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
image-io.cc:169:11: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
     fwrite(p+y*stride,1,width/2,mFH);
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
image-io.cc:174:11: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
     fwrite(p+y*stride,1,width/2,mFH);
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
image-io.cc: In member function 'virtual void PacketSink_File::send_packet(const uint8_t*, int)':
image-io.cc:209:9: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
   fwrite(startCode,1,3,mFH);
   ~~~~~~^~~~~~~~~~~~~~~~~~~
image-io.cc:210:9: error: ignoring return value of 'size_t fwrite(const void*, size_t, size_t, FILE*)', declared with attribute warn_unused_result [-Werror=unused-result]
   fwrite(data,1,n,mFH);
   ~~~~~~^~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[3]: *** [Makefile:778: libde265_la-image-io.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/libde265_la-decctx.Tpo .deps/libde265_la-decctx.Plo
mv -f .deps/libde265_la-dpb.Tpo .deps/libde265_la-dpb.Plo
libtool: compile:  $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++ -DHAVE_CONFIG_H -I. -I.. -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX/include -DLIBDE265_EXPORTS -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/libde265-1.0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -Werror=return-type -Werror=unused-result -Werror=reorder -DDE265_LOG_ERROR -MT libde265_la-image.lo -MD -MP -MF .deps/libde265_la-image.Tpo -c image.cc -o libde265_la-image.o >/dev/null 2>&1
mv -f .deps/libde265_la-image.Tpo .deps/libde265_la-image.Plo
make[3]: Leaving directory '$SRC_DIR/libde265'
make[2]: *** [Makefile:952: all-recursive] Error 1
make[2]: Leaving directory '$SRC_DIR/libde265'
make[1]: *** [Makefile:500: all-recursive] Error 1
make[1]: Leaving directory '$SRC_DIR'
make: *** [Makefile:409: all] Error 2
```

Below is the recipe:

* `meta.yaml`
```
{% set name = "libde265" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/strukturag/{{name}}/releases/download/v{{version}}/{{name}}-{{version}}.tar.gz
  sha256: e4206185a7c67d3b797d6537df8dcaa6e5fd5a5f93bd14e65a755c33cd645f7a

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('cxx') }}

test:
  commands:
    - rd-curves
    - hdrcopy
    - bjoentegaard
    - tests
    - gen-enc-table
    - dec265
    - enc265
    - block-rate-estim
    - yuv-distortion
    - acceleration_speed
 
about:
  home: http://www.libde265.org/
  license: GPL-3
  license_file: COPYING
  summary: 'Open h.265 video codec implementation'

extra:
  recipe-maintainers:
    - sebastian-luna-valero
```

* `build.sh`
```
#!/bin/bash
set -euo pipefail

./configure --prefix=${PREFIX} --disable-dec265 --disable-sherlock265
make -j${CPU_COUNT}
make check
make install
```

Any ideas?

Best regards,
Sebastian

PS: Please let me know if you would like to be a package maintainer.
